name: test1


on:
 pull_request:
    branches: [ main ]


jobs:

 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Pull Request ID
        run: |
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "pr_num=$PR_NUMBER" >> $GITHUB_ENV

      - name: Add Comment to Pull Request if Success
        if: ${{ success() }}
        uses: actions/github-script@v5
        with:
          script: |
            
            pr= await github.rest.pulls.get({
            owner: context.repo.owner, 
            repo: context.repo.repo, 
            pull_number: ${{ env.pr_num }},
              });
            
            console.log("-----------------------------------------------");
            console.log(pr.data.mergeable);
            console.log(pr.data.mergeable_state);
            
            console.log("--------------------------------------------");
            
            
            console.log(pr);
            
            review= await github.rest.pulls.listReviews({
            owner: context.repo.owner, 
            repo: context.repo.repo, 
            pull_number: ${{ env.pr_num }},
              });
            console.log(review);
            
            const string = `Hey \n
            @ydazana\n
            @ilia-intel\n 
            If you use ${{github.event.number}} you will get the PR number on pull request event. \n
            If you use ${{github.event.issue.number}} you will get the PR number on any issue event e.g. updates. \n
            `
            await github.rest.issues.createComment({
            owner: context.repo.owner, 
            repo: context.repo.repo, 
            issue_number: ${{ env.pr_num }},
            body: string
            });

     
