on:
 workflow_run:
    workflows: ["test1"]
    types: [completed]
 pull_request:
    branches: [ main ]


jobs:
 on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
     - run:      echo "HERE"
